### URI base da API
@apiurl = http://localhost:8080/chess/api

### Get chess
GET {{apiurl}}/ HTTP/1.1
Accept: application/json

### Add piece
POST {{apiurl}}/pieces/ HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "piece": [0, 1],
    "position": [1, 1]
}

### Join a client
POST {{apiurl}}/users/ HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "Nuno"
}

### Get all clients
GET {{apiurl}}/users/ HTTP/1.1
Accept: application/json

### Leave a client
DELETE {{apiurl}}/users/Karine HTTP/1.1

### Becoming a player/espectator
PUT {{apiurl}}/users/ HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "Nuno",
    "player": "true"
}