### URI base da API
@apiurl = http://localhost:8080/chess/api

### Get chess
GET {{apiurl}}/ HTTP/1.1
Accept: application/json

### Move piece
PUT {{apiurl}}/pieces/ HTTP/1.1
Accept: application/json
Content-Type: application/json

[ {
    "type": [1, 0],
    "position": [-1, -1]
  },
  {
    "position": [4, 5]
  }
]

### Clean board
PUT {{apiurl}}/board/clean HTTP/1.1
Accept: application/json

### Rearrange board
PUT {{apiurl}}/board/rearrange HTTP/1.1
Accept: application/json

### Join a user
POST {{apiurl}}/users/ HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "Nuno"
}

### Get all users
GET {{apiurl}}/users/ HTTP/1.1
Accept: application/json

### Leave a user
DELETE {{apiurl}}/users/Karine HTTP/1.1

### Becoming a player/espectator
PUT {{apiurl}}/users/ HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "username": "Windoh",
    "player": "false"
}

### Send a message
POST {{apiurl}}/chat/ HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "user": "Karine",
    "content": "Mensagem qualquer"
}